# Generated by Django 2.1.2 on 2018-11-06 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postpicture', models.ImageField(upload_to='postpic')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PostDetail', to=settings.AUTH_USER_MODEL)),
                ('users_stared', models.ManyToManyField(related_name='user_stared', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
