# Generated by Django 2.1.2 on 2018-11-18 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdetail',
            name='users_stared',
        ),
        migrations.AddField(
            model_name='postdetail',
            name='users_stared1',
            field=models.ManyToManyField(related_name='user_stared1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postdetail',
            name='users_stared2',
            field=models.ManyToManyField(related_name='user_stared2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postdetail',
            name='users_stared3',
            field=models.ManyToManyField(related_name='user_stared3', to=settings.AUTH_USER_MODEL),
        ),
    ]
