# Generated by Django 2.1.2 on 2018-12-31 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20181210_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdetail',
            name='users_stared1',
        ),
        migrations.RemoveField(
            model_name='postdetail',
            name='users_stared2',
        ),
        migrations.RemoveField(
            model_name='postdetail',
            name='users_stared3',
        ),
    ]
