# Generated by Django 2.1.2 on 2018-11-06 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20181028_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='fanandfanned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fanned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fanned', to=settings.AUTH_USER_MODEL)),
                ('fans', models.ManyToManyField(blank=True, related_name='fans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='league',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaguename', models.CharField(max_length=200, null=True)),
                ('leaguescore', models.IntegerField(default=0)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('members', models.ManyToManyField(blank=True, related_name='league', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='profilescore',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='profilestatus',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
