# Generated by Django 2.1.2 on 2018-11-07 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20181105_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('members', models.ManyToManyField(blank=True, related_name='category', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='league',
            name='members',
        ),
        migrations.AddField(
            model_name='league',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='league', to='accounts.categories'),
        ),
    ]
