# Generated by Django 2.1.2 on 2018-11-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181106_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='leagueself',
            field=models.ManyToManyField(related_name='blah', to='accounts.league'),
        ),
    ]
