# Generated by Django 2.1.2 on 2018-11-07 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_league_leagueself'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='members',
        ),
        migrations.RemoveField(
            model_name='league',
            name='category',
        ),
        migrations.RemoveField(
            model_name='league',
            name='leagueself',
        ),
        migrations.AddField(
            model_name='categories',
            name='league',
            field=models.ManyToManyField(blank=True, related_name='league', to='accounts.league'),
        ),
        migrations.AddField(
            model_name='league',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='category', to=settings.AUTH_USER_MODEL),
        ),
    ]
