# Generated by Django 2.1.2 on 2018-11-07 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181106_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='league',
        ),
        migrations.AddField(
            model_name='league',
            name='categoryname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoryname', to='accounts.categories'),
        ),
        migrations.AlterField(
            model_name='league',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
