# Generated by Django 2.1.2 on 2018-11-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181106_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='piccredits',
            field=models.IntegerField(default=2),
        ),
    ]
