# Generated by Django 2.1.2 on 2018-11-12 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_randomleague'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='randomleague',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
