# Generated by Django 2.1.2 on 2018-11-12 23:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20181112_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='start',
        ),
        migrations.RemoveField(
            model_name='randomleague',
            name='start',
        ),
        migrations.AddField(
            model_name='league',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 23, 54, 10, 634330, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='randomleague',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 23, 54, 10, 634330, tzinfo=utc)),
        ),
    ]
