# Generated by Django 2.1.2 on 2018-11-13 03:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20181112_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='leaguescore',
        ),
        migrations.AddField(
            model_name='profile',
            name='leaguescore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='league',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 3, 39, 10, 890625, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='randomleague',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 3, 39, 10, 890625, tzinfo=utc)),
        ),
    ]
