# Generated by Django 2.1.2 on 2018-11-14 23:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20181112_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='categoryname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoryname', to='accounts.categories'),
        ),
        migrations.AlterField(
            model_name='league',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 23, 7, 22, 354921, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='randomleague',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 23, 7, 22, 354921, tzinfo=utc)),
        ),
    ]
