# Generated by Django 2.1.2 on 2018-11-15 00:54

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_auto_20181114_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaguename', models.CharField(max_length=200, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 11, 15, 0, 54, 5, 520947, tzinfo=utc))),
                ('members', models.ManyToManyField(blank=True, related_name='TeamLeagueMembers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='randomleague',
            name='members',
        ),
        migrations.AlterField(
            model_name='league',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 0, 54, 5, 520947, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='randomleague',
        ),
    ]
