# Generated by Django 2.1.2 on 2018-11-15 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20181114_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 1, 23, 55, 221406, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teamleague',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 1, 23, 55, 221406, tzinfo=utc)),
        ),
    ]
