# Generated by Django 2.1.2 on 2018-11-15 01:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20181114_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 1, 28, 12, 705580, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teamleague',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 1, 28, 12, 709579, tzinfo=utc)),
        ),
    ]
