# Generated by Django 2.1.2 on 2018-11-15 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20181114_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teamleague',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
