# Generated by Django 2.1.2 on 2018-11-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_winners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winners',
            name='winnerleaguename',
        ),
        migrations.AddField(
            model_name='winners',
            name='winnerleaguename',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
