# Generated by Django 2.1.2 on 2018-11-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20181119_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='winners',
            name='leaguescore',
            field=models.IntegerField(default=0),
        ),
    ]
