# Generated by Django 2.1.2 on 2018-11-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20181119_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='leaguescore',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='profile',
            name='piccredits',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilescore',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='winners',
            name='leaguescore',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=19),
        ),
    ]
