# Generated by Django 2.1.2 on 2018-11-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20181119_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='categoryname',
        ),
        migrations.RemoveField(
            model_name='league',
            name='members',
        ),
        migrations.RemoveField(
            model_name='teamleague',
            name='members',
        ),
        migrations.RemoveField(
            model_name='winners',
            name='winningmembers',
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='league',
        ),
        migrations.DeleteModel(
            name='TeamLeague',
        ),
        migrations.DeleteModel(
            name='winners',
        ),
    ]
