# Generated by Django 2.1.2 on 2018-11-27 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0023_auto_20181122_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanandfanned',
            name='fanned',
        ),
        migrations.AddField(
            model_name='fanandfanned',
            name='fanned',
            field=models.ManyToManyField(blank=True, related_name='fans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='fanandfanned',
            name='fans',
        ),
        migrations.AddField(
            model_name='fanandfanned',
            name='fans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fanned', to=settings.AUTH_USER_MODEL),
        ),
    ]
