# Generated by Django 2.1.2 on 2018-11-27 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20181126_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanandfanned',
            name='fanned',
            field=models.ManyToManyField(blank=True, related_name='fanned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fanandfanned',
            name='fans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fans', to=settings.AUTH_USER_MODEL),
        ),
    ]
