# Generated by Django 2.1.2 on 2018-11-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20181126_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='piccredits',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=19),
        ),
    ]
