# Generated by Django 2.1.2 on 2018-12-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20181128_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilestatus',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
