# Generated by Django 2.1.2 on 2018-11-27 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Leagues', '0002_auto_20181126_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomleague',
            name='members',
        ),
        migrations.AddField(
            model_name='randomleague',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RandomLeagueMembers', to=settings.AUTH_USER_MODEL),
        ),
    ]
