# Generated by Django 2.1.2 on 2018-11-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leagues', '0003_auto_20181127_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomleague',
            name='categoryname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
