# Generated by Django 2.1.2 on 2018-11-28 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leagues', '0004_randomleague_categoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeleague',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Leagues.Categories'),
        ),
    ]
