# Generated by Django 2.1.2 on 2018-11-28 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leagues', '0005_freeleague_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='winners',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Leagues.Categories'),
        ),
    ]
