# Generated by Django 2.1.2 on 2018-12-05 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Leagues', '0006_winners_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeLeagueChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FreeLeagueChat', to='Leagues.FreeLeague')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
