# Generated by Django 3.0.5 on 2020-06-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leagues', '0009_auto_20190206_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winners',
            name='category',
        ),
        migrations.AlterField(
            model_name='freeleague',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
