# Generated by Django 3.0.5 on 2020-06-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leagues', '0010_auto_20200621_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='winners',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
