# Generated by Django 3.0.5 on 2020-06-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leagues', '0011_winners_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomLeague',
        ),
    ]
